export interface Item {
  tag: string;
  correctAnswer: string;
}

export class Items {
  static items = [
    { tag: 'AmmoBox_01', correctAnswer: 'SET_ME' },
    { tag: 'AppleHalf_01', correctAnswer: 'SET_ME' },
    { tag: 'Apple_01', correctAnswer: 'SET_ME' },
    { tag: 'Apple_02', correctAnswer: 'SET_ME' },
    { tag: 'Axe_01', correctAnswer: 'SET_ME' },
    { tag: 'Banana_01', correctAnswer: 'SET_ME' },
    { tag: 'Bandages_01', correctAnswer: 'SET_ME' },
    { tag: 'Bat_01', correctAnswer: 'SET_ME' },
    { tag: 'Bat_02', correctAnswer: 'SET_ME' },
    { tag: 'Baton_01', correctAnswer: 'SET_ME' },
    { tag: 'Beer_01', correctAnswer: 'SET_ME' },
    { tag: 'Beer_02', correctAnswer: 'SET_ME' },
    { tag: 'Beer_03', correctAnswer: 'SET_ME' },
    { tag: 'Binoculars_01', correctAnswer: 'SET_ME' },
    { tag: 'Book_01', correctAnswer: 'SET_ME' },
    { tag: 'Book_02', correctAnswer: 'SET_ME' },
    { tag: 'Book_03', correctAnswer: 'SET_ME' },
    { tag: 'Book_04', correctAnswer: 'SET_ME' },
    { tag: 'BoomBox_01', correctAnswer: 'SET_ME' },
    { tag: 'BriefCase_01', correctAnswer: 'SET_ME' },
    { tag: 'BriefCase_02', correctAnswer: 'SET_ME' },
    { tag: 'BriefCase_03', correctAnswer: 'SET_ME' },
    { tag: 'Bucket_01', correctAnswer: 'SET_ME' },
    { tag: 'Bucket_02', correctAnswer: 'SET_ME' },
    { tag: 'Bucket_03', correctAnswer: 'SET_ME' },
    { tag: 'Burger_01', correctAnswer: 'SET_ME' },
    { tag: 'Cake_01', correctAnswer: 'SET_ME' },
    { tag: 'Cake_02', correctAnswer: 'SET_ME' },
    { tag: 'Camera_01', correctAnswer: 'SET_ME' },
    { tag: 'Carrot_01', correctAnswer: 'SET_ME' },
    { tag: 'Cash_01', correctAnswer: 'SET_ME' },
    { tag: 'Cash_02', correctAnswer: 'SET_ME' },
    { tag: 'Cash_03', correctAnswer: 'SET_ME' },
    { tag: 'ChainSaw_01', correctAnswer: 'SET_ME' },
    { tag: 'ChainSaw_02', correctAnswer: 'SET_ME' },
    { tag: 'ChainSaw_03', correctAnswer: 'SET_ME' },
    { tag: 'ChickenMeat_01', correctAnswer: 'SET_ME' },
    { tag: 'Chiller_01', correctAnswer: 'SET_ME' },
    { tag: 'Chiller_02', correctAnswer: 'SET_ME' },
    { tag: 'Chiller_03', correctAnswer: 'SET_ME' },
    { tag: 'ChocolateBar_01', correctAnswer: 'SET_ME' },
    { tag: 'ChocolateBar_02', correctAnswer: 'SET_ME' },
    { tag: 'ChocolateBar_03', correctAnswer: 'SET_ME' },
    { tag: 'Cigar_01', correctAnswer: 'SET_ME' },
    { tag: 'Cigar_02', correctAnswer: 'SET_ME' },
    { tag: 'Cigar_03', correctAnswer: 'SET_ME' },
    { tag: 'Cigar_04', correctAnswer: 'SET_ME' },
    { tag: 'Ciggie_01', correctAnswer: 'SET_ME' },
    { tag: 'Ciggie_02', correctAnswer: 'SET_ME' },
    { tag: 'Cleaver_01', correctAnswer: 'SET_ME' },
    { tag: 'CoffeeCup_01', correctAnswer: 'SET_ME' },
    { tag: 'CoffeeCup_02', correctAnswer: 'SET_ME' },
    { tag: 'CoffeeCup_03', correctAnswer: 'SET_ME' },
    { tag: 'Coin_01', correctAnswer: 'SET_ME' },
    { tag: 'Coin_02', correctAnswer: 'SET_ME' },
    { tag: 'Cookie_01', correctAnswer: 'SET_ME' },
    { tag: 'Corn_01', correctAnswer: 'SET_ME' },
    { tag: 'Corn_02', correctAnswer: 'SET_ME' },
    { tag: 'CrowBar_01', correctAnswer: 'SET_ME' },
    { tag: 'CupCake_01', correctAnswer: 'SET_ME' },
    { tag: 'CupCake_02', correctAnswer: 'SET_ME' },
    { tag: 'CupCake_03', correctAnswer: 'SET_ME' },
    { tag: 'Donut_01', correctAnswer: 'SET_ME' },
    { tag: 'Donut_02', correctAnswer: 'SET_ME' },
    { tag: 'Donut_03', correctAnswer: 'SET_ME' },
    { tag: 'Donut_04', correctAnswer: 'SET_ME' },
    { tag: 'Drill_01', correctAnswer: 'SET_ME' },
    { tag: 'Drill_02', correctAnswer: 'SET_ME' },
    { tag: 'Drill_03', correctAnswer: 'SET_ME' },
    { tag: 'EnergyCan_01', correctAnswer: 'SET_ME' },
    { tag: 'EnergyCan_02', correctAnswer: 'SET_ME' },
    { tag: 'FireAxe_01', correctAnswer: 'SET_ME' },
    { tag: 'Flare_01', correctAnswer: 'SET_ME' },
    { tag: 'Flare_02', correctAnswer: 'SET_ME' },
    { tag: 'Flare_03', correctAnswer: 'SET_ME' },
    { tag: 'FlashLight_01', correctAnswer: 'SET_ME' },
    { tag: 'FryPan_01', correctAnswer: 'SET_ME' },
    { tag: 'FuelCan_01', correctAnswer: 'SET_ME' },
    { tag: 'GolfClub_01', correctAnswer: 'SET_ME' },
    { tag: 'Hammer_01', correctAnswer: 'SET_ME' },
    { tag: 'Handbag_01 1', correctAnswer: 'SET_ME' },
    { tag: 'Handbag_01', correctAnswer: 'SET_ME' },
    { tag: 'Handbag_02', correctAnswer: 'SET_ME' },
    { tag: 'Handbag_03', correctAnswer: 'SET_ME' },
    { tag: 'Handbag_04', correctAnswer: 'SET_ME' },
    { tag: 'Handbag_05', correctAnswer: 'SET_ME' },
    { tag: 'Handbag_06', correctAnswer: 'SET_ME' },
    { tag: 'HealthPack_01', correctAnswer: 'SET_ME' },
    { tag: 'HotDog_01', correctAnswer: 'SET_ME' },
    { tag: 'IceBlock_01', correctAnswer: 'SET_ME' },
    { tag: 'IceBlock_02', correctAnswer: 'SET_ME' },
    { tag: 'IceBlock_03', correctAnswer: 'SET_ME' },
    { tag: 'IceCreamSundae_01', correctAnswer: 'SET_ME' },
    { tag: 'IceCream_01', correctAnswer: 'SET_ME' },
    { tag: 'IceCream_02', correctAnswer: 'SET_ME' },
    { tag: 'IceCream_03', correctAnswer: 'SET_ME' },
    { tag: 'Jam_01', correctAnswer: 'SET_ME' },
    { tag: 'Jam_02', correctAnswer: 'SET_ME' },
    { tag: 'Jam_03', correctAnswer: 'SET_ME' },
    { tag: 'Jam_04', correctAnswer: 'SET_ME' },
    { tag: 'KiwiFruit_01', correctAnswer: 'SET_ME' },
    { tag: 'Knife_01', correctAnswer: 'SET_ME' },
    { tag: 'Knife_02', correctAnswer: 'SET_ME' },
    { tag: 'Longboard_01', correctAnswer: 'SET_ME' },
    { tag: 'Longboard_02', correctAnswer: 'SET_ME' },
    { tag: 'Machete_01', correctAnswer: 'SET_ME' },
    { tag: 'MedicBox_01', correctAnswer: 'SET_ME' },
    { tag: 'MetalPipe_03', correctAnswer: 'SET_ME' },
    { tag: 'MilkBottle_01', correctAnswer: 'SET_ME' },
    { tag: 'MilkBottle_02', correctAnswer: 'SET_ME' },
    { tag: 'MilkCarton_01', correctAnswer: 'SET_ME' },
    { tag: 'MilkCarton_02', correctAnswer: 'SET_ME' },
    { tag: 'Muffin_01', correctAnswer: 'SET_ME' },
    { tag: 'Muffin_02', correctAnswer: 'SET_ME' },
    { tag: 'Muffin_03', correctAnswer: 'SET_ME' },
    { tag: 'Needle_01', correctAnswer: 'SET_ME' },
    { tag: 'NewsPaper_01', correctAnswer: 'SET_ME' },
    { tag: 'PaperBottle_01', correctAnswer: 'SET_ME' },
    { tag: 'PaperBottle_02', correctAnswer: 'SET_ME' },
    { tag: 'Pie_01', correctAnswer: 'SET_ME' },
    { tag: 'Pie_02', correctAnswer: 'SET_ME' },
    { tag: 'Pie_03', correctAnswer: 'SET_ME' },
    { tag: 'Pills_01', correctAnswer: 'SET_ME' },
    { tag: 'Pills_02', correctAnswer: 'SET_ME' },
    { tag: 'Pipe_01', correctAnswer: 'SET_ME' },
    { tag: 'Pipe_02', correctAnswer: 'SET_ME' },
    { tag: 'Pizza_01', correctAnswer: 'SET_ME' },
    { tag: 'Plank_01', correctAnswer: 'SET_ME' },
    { tag: 'PlasticCoffeeCup_01', correctAnswer: 'SET_ME' },
    { tag: 'PlasticCoffeeCup_02', correctAnswer: 'SET_ME' },
    { tag: 'Plunger_01', correctAnswer: 'SET_ME' },
    { tag: 'PopCorn_01', correctAnswer: 'SET_ME' },
    { tag: 'RolledPaper_01', correctAnswer: 'SET_ME' },
    { tag: 'Sandwich_01', correctAnswer: 'SET_ME' },
    { tag: 'ScrewDriver_01', correctAnswer: 'SET_ME' },
    { tag: 'ScrewDriver_02', correctAnswer: 'SET_ME' },
    { tag: 'ScrewDriver_03', correctAnswer: 'SET_ME' },
    { tag: 'Skateboard_01', correctAnswer: 'SET_ME' },
    { tag: 'SledgeHammer_01', correctAnswer: 'SET_ME' },
    { tag: 'SmartPhone_01', correctAnswer: 'SET_ME' },
    { tag: 'SmartPhone_02', correctAnswer: 'SET_ME' },
    { tag: 'SmartPhone_03', correctAnswer: 'SET_ME' },
    { tag: 'SmartPhone_04', correctAnswer: 'SET_ME' },
    { tag: 'SmartPhone_05', correctAnswer: 'SET_ME' },
    { tag: 'SmartPhone_06', correctAnswer: 'SET_ME' },
    { tag: 'SmartPhone_07', correctAnswer: 'SET_ME' },
    { tag: 'SmartPhone_08', correctAnswer: 'SET_ME' },
    { tag: 'SodaCan_01', correctAnswer: 'SET_ME' },
    { tag: 'SodaCan_02', correctAnswer: 'SET_ME' },
    { tag: 'SodaCan_03', correctAnswer: 'SET_ME' },
    { tag: 'Spade_01', correctAnswer: 'SET_ME' },
    { tag: 'Spanner_01', correctAnswer: 'SET_ME' },
    { tag: 'Spatula_01', correctAnswer: 'SET_ME' },
    { tag: 'SportsBag_01', correctAnswer: 'SET_ME' },
    { tag: 'SportsBag_02', correctAnswer: 'SET_ME' },
    { tag: 'SportsBag_03', correctAnswer: 'SET_ME' },
    { tag: 'SteakMeat_01', correctAnswer: 'SET_ME' },
    { tag: 'StrawCup_01', correctAnswer: 'SET_ME' },
    { tag: 'StrawCup_02', correctAnswer: 'SET_ME' },
    { tag: 'Sword_01', correctAnswer: 'SET_ME' },
    { tag: 'Tablet_01 1', correctAnswer: 'SET_ME' },
    { tag: 'Tablet_01', correctAnswer: 'SET_ME' },
    { tag: 'Tablet_02', correctAnswer: 'SET_ME' },
    { tag: 'Tablet_03', correctAnswer: 'SET_ME' },
    { tag: 'Taco_01', correctAnswer: 'SET_ME' },
    { tag: 'ToolBox_01', correctAnswer: 'SET_ME' },
    { tag: 'ToolBox_02', correctAnswer: 'SET_ME' },
    { tag: 'ToolBox_03', correctAnswer: 'SET_ME' },
    { tag: 'WalkieTalkie_01', correctAnswer: 'SET_ME' },
    { tag: 'WalkieTalkie_02', correctAnswer: 'SET_ME' },
    { tag: 'WalkieTalkie_03', correctAnswer: 'SET_ME' },
    { tag: 'WalkingStick_01', correctAnswer: 'SET_ME' },
    { tag: 'WaterBottle_01', correctAnswer: 'SET_ME' },
    { tag: 'WaterBottle_02', correctAnswer: 'SET_ME' },
    { tag: 'Weight_01', correctAnswer: 'SET_ME' },
    { tag: 'Weight_02', correctAnswer: 'SET_ME' },
    { tag: 'Wine_01', correctAnswer: 'SET_ME' },
    { tag: 'Wine_02', correctAnswer: 'SET_ME' },
    { tag: 'Wine_03', correctAnswer: 'SET_ME' },
    { tag: 'WoodPlank_01', correctAnswer: 'SET_ME' },
    { tag: 'Wrench_01', correctAnswer: 'SET_ME' },
  ];

  public static getRandomItem(socket): Item {
    if (socket.data.lastItem === undefined) {
      socket.data.lastItem = 0;
    } else {
      socket.data.lastItem++;
    }

    if (socket.data.lastItem > Items.items.length - 1) {
      socket.data.lastItem = Items.items.length - 1;
    }

    return Items.items[socket.data.lastItem];
  }
}
